4dn-dcic/tibanna

tibanna/check_task.py
This function includes the creation of two different format strings that were bugged. The second message doesn't have the format arguments grouped correctly (needed to add parenthesis).
Both error messages include the same bug related to precedence in python. Specifcally, "%" has a higher precedence than "+" regardless of what types are interacting with the operator. As a result, python was trying to evaluate the format string before concattenating the format strings which raises an error due to having non matching numbers of "%s" and arguments. I've fixed this bug by switching the string concatenation to an alternative style. Specifcally, strings inside parenthesis that aren't separated by commas are automatically concatenated by python.
=> Error message fixes for terminate_idle_instance function

tests/tibanna/unicorn/test_ec2_utils.py, tibanna/__main__.py, tibanna/check_task.py, tibanna/core.py, tibanna/cw_utils.py, tibanna/pricing_utils.py
- Added `Estimated_Cost_Type` to the `metrics_report.tsv`. It can be "immediate estimate", "actual cost" or "retrospective estimate". The plot metrics html has been modified accordingly. `cost_estimate` will also return this together with the estimate
- `plot_metrics` now tries to retrieve the cost estimate from the tsv instead of calculating it every time the command is run (more accurate since AWS prices change over time).
- `cost_estimate -j ... -u` now does not update the tsv, if the estimate is retrospective and an immediate estimate (or actual cost) is already in the tsv.
=> Add cost estimate type

awsf3/target.py, docs/api.rst, docs/commands.rst, docs/execution_json.rst, tests/awsf3/test_target.py, tests/tibanna/unicorn/run_task_awsem/event_tagging.json, tibanna/_version.py, tibanna/iam_utils.py
Allow tagging of output files by adding a tag key:
```
"output_target": {
"report": {
"object_key": "output/my_first_md5_report_tagged",
"tag" : "Key1=Value1&Key2=Value2"
}
},
```
You can try it with `"awsf_image": "aveit/tibanna-awsf:1.1.2.dev5",`
=> Allow tagging of output files

tibanna/_version.py, tibanna/core.py
* jobid can be provided in input json (can be overwritten by run_workflow's jobid option)
* run_workflow response's response->executionArn points to the correct execution not the costupdater execution.
=> return execArn for run_workflow

docs/news.rst
Updated link to public DOI instead of routing through a Harvard proxy.
=> Updated link to public DOI instead of routing through a Harvard proxy.

awsf3/aws_run_workflow_generic.sh, awsf3/spot_failure_detection.sh, docs/monitoring.rst, tibanna/_version.py, tibanna/iam_utils.py
If a workflow is run on a spot instance, a new cron job will regularly check for the AWS termination notice in the EC2 metadata. If the termination notice is detected, a file `JOBID.spot_failure` is created in the S3 log bucket.
The preinstalled `ec2metadata` package is old and does not provide the required `/spot/instance-action` endpoint. We therefore check directly for that meta data using the instance metadata service (v1) as described here: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html
The functionality of the cron script has been tested using an EC2 metadata mocking library.
=> Spot failure detection

tibanna/top.py
If one of the top commands contain double quotes, the metrics report (CPU, memory usage) is currently broken.
=> Fix metrics report, when top commands contain double quotes

tibanna/core.py
Reason: we want to be able to modify ami_id in a sub classes.
No version bump, as the previous version has not been released.
=> Make ami_id an attribute of the API class

tibanna/_version.py, tibanna/ec2_utils.py
This PR adds the configuration option `ami_id`, which makes the used AMI for the EC2 instance configurable.
=> Make ami_id configurable

awsf3-docker/run.sh, tibanna/_version.py
This PR adds the `--custom-net host` option to the `cwltool` command, so that the docker container that is started by `cwltool` uses the network configuration of the host.
=> Pass custom-net option to cwltool

awsf3-docker/run.sh, awsf3/utils.py, docs/execution_json.rst, docs/wdl.rst, tests/awsf3/test_utils.py, tibanna/_version.py, tibanna/awsem.py, tibanna/ec2_utils.py
With this change, additional command line arguments can be specified in the tibanna job description that are passed to the `cwltool`, `cromwell run`, `caper run` commands.
This is necessary, e.g., for the ChipSeq pipeline that only runs using `caper run ... --docker`. In this case we can now specify `"run_args": "--docker"` in the job description.
=> Add run_args to specify additional command line arguments

awsf3/aws_run_workflow_generic.sh, awsf3/cloudwatch_agent_config.json, docs/monitoring.rst, pyproject.toml, tibanna/cw_utils.py, tibanna/iam_utils.py
This PR removes the use of the deprecated CloudWatchMonitoringScripts and switches to Cloudwatch agent to collect metrics from the EC2.
=> Use Cloudwatch agent to collect metrics

poetry.lock, pyproject.toml, tibanna/lambdas/requirements.txt
This PR pins the `requests` version to the previous minor version. The latest version leads to a dependency warning when running `cwltool`. However, it is unclear if that warning actually has a negative effect.
I also removed the `urllib3` dependency. It is not used explicitly anywhere and is installed with `botocore` anyway.
=> Pin `requests` version

CHANGELOG.rst, awsf3-docker/Dockerfile, awsf3-docker/run.sh, docs/ami.rst, pyproject.toml, scripts/publish-docker, tibanna/ec2_utils.py
- `arm_per_region` is now configurable as config option. This is required to make it compatible to `tibanna_ff`, where we need to overwrite the used AMIs
- Singularity was not working at all. This has been fixed together with a `cwltool` version bump. Also, it is now working on ARM instances. An ARM/AMD Singularity `.deb`  package has been compiled for simpler installation in the Tibanna docker image. These packages are pulled from S3.
- The docker build time has been reduced as all installations from source have been removed
- Mounting via Goofys has been fixed for ARM instances
=> Add `arm_per_region` as option, fix Singularity, reduce build time

awsf3/aws_run_workflow_generic.sh, awsf3/cloudwatch_agent_config.json, poetry.lock, pyproject.toml, tests/tibanna/unicorn/test_ec2_utils.py, tibanna/check_task.py, tibanna/cw_utils.py, tibanna/ec2_utils.py, tibanna/lambdas/requirements.txt, tibanna/vars.py
- This PR Increases the metrics interval collection by Cloudwatch to 120s (from 60s). When many and long workflows are run a 60s interval is too costly. The `plot_metrics` command has been adjusted accordingly.
- We enforce a new version of Benchmark, which resolves issue #382.
- `instance_type` now takes precedence over `cpu`,`mem`. When both is specified, `cpu`,`mem` will be ignored and Benchmark will not be used. To use Benchmark, `instance_type` may not be specified in the job description.
- Added instance termination commands at various places in the `check_task` lambda as failsafe in case the instance does not correctly shut down after the workflow is run.
- Improved fleet error handling by looking at all returned error codes
=> Improved fleet error handling + smaller fixes

CHANGELOG.rst, pyproject.toml, tibanna/core.py
This PR extends the `tibanna stat` command and returns now also the `instance_start_time` in addition to the `execution_start_time`. This is helpful if we want to assess the time that it took to obtain the EC2 instance from AWS.
Old result:
```
tibanna stat --job-ids=jc5RYG75yURz -l
jobid	status	name	start_time	stop_time	instance_id	instance_type	instance_status	ip	key
jc5RYG75yURz	SUCCEEDED	run_bam_to_fastq_paired-end	2023-07-19 17:15	2023-07-19 20:02	-   -	-	-	-
```
New result:
```
tibanna stat --job-ids=jc5RYG75yURz -l
jobid	status	name	execution_start_time	execution_stop_time	instance_id	instance_start_time	instance_type	instance_status	ip	key
jc5RYG75yURz	SUCCEEDED	run_bam_to_fastq_paired-end	2023-07-19 17:15	2023-07-19 20:02	-	2023-07-19 17:16	-	-	-	-
```
I am using the creation …
=> Add `instance_start_time` to `tibanna stat`

.github/workflows/main.yml, CHANGELOG.rst, docs/installation.rst, docs/news.rst, poetry.lock, pyproject.toml, tibanna/lambdas/check_task_awsem.py, tibanna/lambdas/run_task_awsem.py, tibanna/lambdas/update_cost_awsem.py
- Allows Tibanna to be used with Python 3.9 and 3.10
=> Python 3.9/3.10

CHANGELOG.rst, awsf3-docker/Dockerfile, pyproject.toml
Fixes the docker version that we are installing within the awfs docker image. Newer versions will build, but workflows will fail with the following error:
```
/etc/init.d/docker: 62: ulimit: error setting limit (Invalid argument)
```
=> Fix docker version

CHANGELOG.rst, awsf3/aws_run_workflow_generic.sh, docs/execution_json.rst, pyproject.toml, tibanna/ec2_utils.py, tibanna/lambdas/requirements.txt
Add config option `disable_metrics_collection`. Then `true`  it will prevent the installation of the Cloudwatch agent on the EC2 and will therefore disable the metrics collection.
Addresses Issue #401.
=> Add option to disable metrics collection

CHANGELOG.rst, docs/execution_json.rst, pyproject.toml, tibanna/check_task.py, tibanna/core.py, tibanna/cw_utils.py, tibanna/job.py, tibanna/pricing_utils.py, tibanna/top.py, tibanna/vars.py
* Disable idle instance check when `disable_metrics_collection` is active
* Switch to timezone aware datetime object everywhere. In particular, replace deprecated `datetime.utcnow()` with `datetime.now(timezone.utc)`.
* Update docs
=> Timezone-aware datetime objects, `disable_metrics_collection` bugfix

CHANGELOG.rst, pyproject.toml, tibanna/top.py
Safeguard against unexpected output from top command
=> Add safeguard for parsing top command

CHANGELOG.rst, pyproject.toml, tibanna/top.py
The output of the top command can contain the following.
This PR makes sure that the timestamp is retrieved correctly in this case
=> Fix parser for top command output
